### ISSUE TITLE
user transformer fails

### ISSUE THREAD

**Issue by mx2s** [gitcomteam/gitcom-api#59]
Exception: 
```
Object reference not set to an instance of an object.
   at App.PL.Transformer.User.UserTransformer.Transform(Object obj) in /home/mx2s/Files/SideProjects/Current/gitcom/gitcom-api/App/PL/Transformer/User/UserTransformer.cs:line 9
   at App.AL.Controller.Home.MeController.<.ctor>b__1_0(Object _) in /home/mx2s/Files/SideProjects/Current/gitcom/gitcom-api/App/AL/Controller/Me/MeController.cs:line 17
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

```

**Comment by mx2s** [comment]
it was only local issue because of corrupt data
